name: Automation API Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # gradle command for running
    - name: Execute test
      run: ./gradlew apirun

    # debug
    - name: List files in build directory
      run: ls -R build

    # Upload HTML report as an artifact
    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: build/reports/api

