name: Automation API Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Project
      run: ./gradlew build

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # gradle command for running
    - name: Execute test
      run: ./gradlew apirun

    # debug
    - name: List files in build directory
      run: ls -R build

    - name: Debug Report Location
      run: find build -name "report.html"

    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: build/reports/web/report.html
